<a href="https://colab.research.google.com/github/Apotema1/jupiteenotebookPract/blob/main/array_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [3]:
list (range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.zeros(3)

In [5]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand()

0.6085224866008585

In [9]:
np.random.randint(1, 10)

6

In [11]:
np.random.randint(1, 10, (10, 10))

array([[1, 9, 2, 6, 5, 8, 6, 6, 8, 8],
       [3, 1, 8, 4, 2, 9, 9, 5, 5, 8],
       [9, 8, 8, 3, 9, 2, 3, 7, 3, 2],
       [9, 8, 8, 6, 7, 6, 8, 6, 5, 2],
       [1, 7, 8, 3, 5, 5, 5, 1, 4, 3],
       [6, 9, 6, 4, 4, 3, 1, 3, 4, 2],
       [7, 9, 5, 7, 2, 6, 4, 7, 3, 2],
       [6, 5, 9, 8, 8, 7, 7, 4, 4, 4],
       [6, 4, 9, 7, 3, 4, 8, 1, 5, 8],
       [2, 6, 3, 7, 5, 1, 9, 4, 7, 9]])