<a href="https://colab.research.google.com/github/Apotema1/jupiteenotebookPract/blob/main/Shape_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
array = np.random.randint(1,10,(3,2))

In [6]:
array.shape 

(3, 2)

In [7]:
array

array([[1, 9],
       [5, 7],
       [6, 4]])

In [10]:
array.reshape(1,6)

array([[1, 9, 5, 7, 6, 4]])

In [12]:
np.reshape(array,(1,6,),"A")

array([[1, 9, 5, 7, 6, 4]])

In [13]:
np.reshape(array,(2,3),"C")

array([[1, 9, 5],
       [7, 6, 4]])